### ISSUE TITLE
[BUG] Custom backgrounds and images doesn't show up

### ISSUE THREAD

**Issue by xTuCo** [floh22/LeagueBroadcastHub#103]
**Describe the bug**
For example, I replace the "Score.png" file for my custom score background and it doesn't change anything. It continues showing the original one... Why is that happening? Could you help me? Thank you!

**To Reproduce**
1. Go to 'Frontend/ingame/backgrounds'
2. Replace 'Score.png' with my custom file (named the same).
3. Start League Broadcast
4. It shows up the original Score.png even there is not already in the folder

**Expected behavior**
I want to see my custom score BG.

**Material**
![Sense títol](https://user-images.githubusercontent.com/96700452/147418746-54f676a8-8d20-4ec5-8d4c-791b5d35bd80.png)
![Sense títol](https://user-images.githubusercontent.com/96700452/147418769-549189fc-4fb2-4d8f-8387-4f237f87f5f4.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version S/N

**Comment by shinilee** [comment]
this is known issue I fixed this issue by everytime I change the img in the folder I restart the leaguebroadcast and reset the source from obs studio

**Comment by egosykes** [comment]
Hello, I have the same problem. Restarted the LolBroadcast, reset the obs and the default Score still appears. Did anyone find a solution? Thanks

**Comment by figyl** [comment]
You need to modify Config/Ingame.json
