### ISSUE TITLE
[BUG] game.cfg line endings other than CRLF break memory reading

### ISSUE THREAD

**Issue by itscoquini** [floh22/LeagueBroadcastHub#127]
When I start the program this pop-up appears
![image](https://user-images.githubusercontent.com/91434224/154983670-ba07688d-9426-4632-b47d-3f2681117a5e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 21H2 Build 19044.1566
[Log-2022-02-21-16-19.log](https://github.com/floh22/LeagueBroadcast/files/8110362/Log-2022-02-21-16-19.log)

**Comment by floh22** [comment]
`[WARNING] Could not parse game config. Replay API may not be enabled!` looks like the first issue. Can you go into your League install folder, open `Config/game.cfg` and check if there is anything that looks out of the ordinary? Like escape characters such as `\n` or similar. One thing to try is to close league, rename game.cfg to something else, and then start league again.

If that does not help:
1. Can you post your game.cfg?
2. What region/language are you using?
3. Can you upload the replay so I can take a look?

**Comment by itscoquini** [comment]
I don´t have nothing that you mentioned before. Maybe that´s the issue

**Comment by itscoquini** [comment]
This is my game.cfg
[game.txt](https://github.com/floh22/LeagueBroadcast/files/8116656/game.txt)

I'm using EUW and Spanish

**Comment by floh22** [comment]
Can you try changing line endings from `LF` to `CR LF`?

**Comment by itscoquini** [comment]
I think the problem is fixed, thank you very much!

**Comment by floh22** [comment]
i'll keep this issue open so others know this issue still persists and how to fix it
