### ISSUE TITLE
LB closes when "Retrieving latest patch info"

### ISSUE THREAD

**Issue by kaianvn** [floh22/LeagueBroadcastHub#206]
**I'm opening this new issue because the error messages are different than #198. Maybe it could be a mistake in my end.**

The title mostly says it all, I try to open the app, it says **"Retrieving latest patch info"** and it crashes, the log says the following description:

_"The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0."_

When I try to manually access the [https://raw.communitydragon.org/latest/content-metadata.json](https://raw.communitydragon.org/latest/content-metadata.json) that supposedly timed out _("caused a TaskCanceledException")_, it says the following:

_version:
"12.21.4770420+branch.releases-12-21.content.release"_

Here are my logs:
[Log-2022-11-14-01-01.log](https://github.com/floh22/LeagueBroadcast/files/9999367/Log-2022-11-14-01-01.log)
[Crash-2022-11-14-01-01.log](https://github.com/floh22/LeagueBroadcast/files/9999368/Crash-2022-11-14-01-01.log)

**Comment by floh22** [comment]
Fixed in 1.5.37

**Comment by FireFoXz09** [comment]
Problem still there. Here's the logs: 
[Crash-2022-11-26-10-54.log](https://github.com/floh22/LeagueBroadcast/files/10096572/Crash-2022-11-26-10-54.log)
[Log-2022-11-26-10-54-0.log](https://github.com/floh22/LeagueBroadcast/files/10096573/Log-2022-11-26-10-54-0.log)
