### ISSUE TITLE
[Bug] Install location cannot be found when using single backslashes in install location

### ISSUE THREAD

**Issue by Ayvanm** [floh22/LeagueBroadcastHub#210]
**Describe the bug**
Program unable to find league installation on current version

**To Reproduce**
1. Go to 'Config/Component.json' and add "C:\Riot Games"
2. Save and try to execute leaguebroadcast.exe
3. Doesn`t load or crash

**Expected behavior**
mmmm program workin?

**Material**
Added the route

![2](https://user-images.githubusercontent.com/122535710/212072438-c6d7b6e8-2355-44b5-a058-6a6fd0e5df60.png)

Getting this error or the program crashing
![1](https://user-images.githubusercontent.com/122535710/212072515-a8ecede0-eca4-493e-935c-5f2afdc558f9.png)

I tried this solutions in a older post but it didn`t work
![3](https://user-images.githubusercontent.com/122535710/212072725-8a53084b-588d-4669-a0f7-d3204ab038bf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version lattest version

**Comment by Ayvanm** [comment]
[Crash-2023-01-12-09-51.log](https://github.com/floh22/LeagueBroadcast/files/10401772/Crash-2023-01-12-09-51.log)

**Comment by thangoghd** [comment]
at line 55, your Component.json file  is missed a comma

**Comment by Ayvanm** [comment]
> at line 55, your Component.json file is missed a comma

it didn`t work. Same error

**Comment by Ayvanm** [comment]
![4](https://user-images.githubusercontent.com/122535710/212970294-2a58472c-1430-4666-9c12-0c23fda112c8.png)

**Comment by thangoghd** [comment]
Where do you place your Riot Games's folder?

**Comment by Ayvanm** [comment]
> Where do you place your Riot Games's folder?

I only have 1 disk so its "C:\" I got installed 2 Tournaments servers and live. I dont know if this can produce the error

**Comment by thangoghd** [comment]
No man, I mean your  game's folder. For example,  My game folder's  location is D:\Program Files (x86)\Riot Games\League of Legends.
So my Component.json file just added  "D:\\Program Files (x86)"

**Comment by Ayvanm** [comment]
i think that i'm not understanding. My games are in "C:\Riot games" and inside there i got 3 different folders "League of legends, League of legends tournament 1 and League of Legends Tournament 2"

> No man, I mean your game's folder. For example, My game folder's location is D:\Program Files (x86)\Riot Games\League of Legends. So my Component.json file just added "D:\Program Files (x86)"

i think that i'm not understanding. My games are in "C:\Riot games" and inside there i got 3 different folders "League of legends, League of legends tournament 1 and League of Legends Tournament 2"

**Comment by thangoghd** [comment]
"C:\Riot games" or "C:\Riot Games"

**Comment by Ayvanm** [comment]
C:\Riot Games. I did the default installation

**Comment by thangoghd** [comment]
that s strange. May i see your League of Legends folder screenshot?

**Comment by Ayvanm** [comment]
it's in my work's office pc and its 4.38am in Argentina haha but the installation folder it's something like this

![dedf586ecec2a40cdfe9ba0298158f42](https://user-images.githubusercontent.com/122535710/213383363-be34d0bc-63b1-4573-a6d3-15ff57d0c69b.png)

This photo is from my personal computer but it should be something like this

**Comment by thangoghd** [comment]
Doesn't same on me
![League of Legends 1_19_2023 2_54_21 PM (2)](https://user-images.githubusercontent.com/79989589/213385746-60472f78-0359-4984-99ef-da3590f599fb.png)
I think I'll be waiting when you come home

**Comment by Ayvanm** [comment]
![5](https://user-images.githubusercontent.com/122535710/213540149-592c8c73-6ba6-4d2d-8066-7c3df51f0255.png)

**Comment by thangoghd** [comment]
I haven't seen these"League of Legends (Tourament Realm)" folders before.

https://user-images.githubusercontent.com/79989589/213674188-5e52683b-5763-4e7a-ae6c-53ff6f7d0e20.mp4

You should try to go to Riot Cilent and find your game's location.
Sorry, My Riot CIlent can not switch to English. "Tuỳ Chỉnh" is "Setting" , "Liên Minh Huyền Thoại" is "League of Legends" and "Đường dẫn cài đặt" is "Install Location".
I think, maybe (just maybe) these folder "League of Legends (Tourament Realm)" make the program to get the wrong location. Rename to "League of Legends_Tourament Realm"
I tried it with myself, the program is crashed.

**Comment by xcferg** [comment]
![image](https://user-images.githubusercontent.com/20517601/214328554-637f1710-19f1-4eb2-9add-1de9c4a9e3b7.png)
![image](https://user-images.githubusercontent.com/20517601/214328677-6f2818f2-7975-4492-8e36-568ac9c09089.png)
![image](https://user-images.githubusercontent.com/20517601/214328810-cc7cfcab-4eac-4300-8fd2-4218e20d4336.png)
Currently having same issue. I have tried many different ways to fix this problem however it still gives me the same error code. The download is in the default location on installation so I dont know why there is this problem

**Comment by NokkedOut** [comment]
Hey there, having the same/similiar problem. New to League Broadcast and wanted to try it out. Fresh Install, just changed the League Install to my correct Folder (have it installed on second ssd D:). League Broadcast crashing instantly when trying to start. It may be a Windows Version problem? Im on 22h2 since my OS is also freshly setup before i considered using League Broadcast.

**Comment by floh22** [comment]
Is this fixed in the latest update? Try adding the League of Legends folder directly. So the default case would be `C:\\Riot Games  \\League of Legends`, you can also try adding `\\` at the end and see if that helps

**Comment by NokkedOut** [comment]
Unfortunately its not fixed for me in the newest release, if i add the Folder it crashes and doesnt start, if i dont add the folder it starts and says it cant find the install, but if i ignore it and keep starting it, it connects to the client but doesnt show the scoreboard etc. Do you need any logs? Edit: It was working for some time but with the new patch and update it doesnt seem to work anymore but doesnt have to be related

**Comment by floh22** [comment]
If its crashing the latest crash logs would be helpful, I dont see how the latest update or patch could affect it, so looks like some kind of instability to me

**Comment by NokkedOut** [comment]
After adding my path D:\Games\Riot Games\\ into the component as a separate line or replacing D:\\ for example, it only starts for like 1 sec and then crashes. Here is the crashlog and component.json. [Crash-2023-02-25-15-21.log](https://github.com/floh22/LeagueBroadcast/files/10831353/Crash-2023-02-25-15-21.log)
[Component.zip](https://github.com/floh22/LeagueBroadcast/files/10831371/Component.zip)

**Comment by floh22** [comment]
Change `D:\Games\Riot Games` to `D:\\Games\\Riot Games`.

This is an artifact of json deserializtation and me originally writing this as a prototype and not something to be widely used

**Comment by NokkedOut** [comment]
Alright, this fixed the crash, but it still says it cant find the League Install. As before when i dont close it and ignore it, it starts and works kindof? It doesnt use the custom images as backgrounds for scoreboard, gold graph etc...

**Comment by NokkedOut** [comment]
Update, i just moved the game install to the standard C:\Riot Games and now it doesnt give the error when starting. So i guess now i just have to fix the ingame.json and it using the correct images

**Comment by floh22** [comment]
alright, can you by any chance show the structure of your Riot Games folder? Would be good to solve this issue for others in the future

**Comment by ddt442** [comment]
Same problem here.
shows error but game connected.

`C:\Riot Games\League of Legends`

My structure.

**Comment by Ayvanm** [comment]
With the new update the client connects but i wont show gold/min, cs/min, items, lvl, etc

**Comment by Petkoww** [comment]
Greetings, I have the same problem and cant seem to fix it. I tried everything and if the program wont crash it will show that it cant find the game. When I click cancel and try to connect to league client it literally crashes.....

**Comment by Petkoww** [comment]
Ok so I have looked around and the program is literally unstable. It loads sometimes, it connect and then crashes or it crashes and doesnt connect.
