### ISSUE TITLE
[BUG] Can't read ingame Gold

### ISSUE THREAD

**Issue by shinilee** [floh22/LeagueBroadcastHub#64]
![image](https://user-images.githubusercontent.com/82671596/130891404-7394d58d-c421-4890-b1ff-28511007d571.png)
[Log-2021-08-25-22-39.log](https://github.com/floh22/LeagueBroadcast/files/7051126/Log-2021-08-25-22-39.log)
can't read ingame blue, red team gold

**Comment by alexissosa88** [comment]
Idem Problem

**Comment by shinilee** [comment]
> Idem Problem

what is that mean Idem Problem?

**Comment by shinilee** [comment]
I also having problem with Objective Pop Ups / Spawn and Leveling Popup and Item Popup not working

**Comment by floh22** [comment]
Could you set the log level to Verbose and send that log file? It should be far larger. It might also help if you can send a replay of a game where this issue happens

**Comment by overkido** [comment]
any replay is giving an error and does not count the gold, does not show the experience of each character, levalup also does not appear.
[Crash-2021-08-25-18-40.log](https://github.com/floh22/LeagueBroadcast/files/7056169/Crash-2021-08-25-18-40.log)
![image](https://user-images.githubusercontent.com/89580284/130946861-7890c91a-2297-477b-915d-ae5ef3a1d14c.png)

**Comment by shinilee** [comment]
Baron Power Play Popup but Gold stay in 0 Timer working
Elder Timer Couldn't test
Inhibitor Timers Working
Objective Pop Ups Spawn Dragon Spawn Not Working, Rift Spawn Not Working, Baron Spawn Working
Objective Pop Ups Kill Working
Item Notifications Not Working
Level Up Notifications Not Working
EXP Tab Pop up appears but Numbers doesn't change
Gold Tab Pop up appears but Numbers doesn't change
CS Per Min. Working
Scoreboard Working everything except Team Gold
Team Names Working
Team Scores Working
Team Icons Working
Gold Graph Popup appears but no graphs
[Log-2021-08-26-09-27.log](https://github.com/floh22/LeagueBroadcast/files/7060149/Log-2021-08-26-09-27.log)
[Log-2021-08-26-09-32.log](https://github.com/floh22/LeagueBroadcast/files/7060150/Log-2021-08-26-09-32.log)
[Log-2021-08-26-09-27-0.log](https://github.com/floh22/LeagueBroadcast/files/7060151/Log-2021-08-26-09-27-0.log)

**Comment by shinilee** [comment]
can't upload replay too big I search CQ AWM and tested on all recent game on NA server

**Comment by OrionCodeDev** [comment]
Update Offsets to latest version, same problem i fixed it in that way. Cheers

**Comment by shinilee** [comment]
> Update Offsets to latest version, same problem i fixed it in that way. Cheers

is that mean I can use it now? or do i have to wait until the update?

**Comment by overkido** [comment]
my already updated i downloaded again updated and still buggy, i have championship to transmit s´frill semi final and will be without the overlay if n comes back to work.

**Comment by floh22** [comment]
Issue should be fixed permanently in next versions, but for now I have added a workaround.

Riot has not updated DDragon, so it still says 11.16, while the client is on 11.17. I accidentally used the DDrag version instead of local client version when determining which offsets to fetch from github.
